package com.xmrbi.unware.component.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xmrbi.unware.data.entity.main.StoreHouse;
import com.xmrbi.unware.data.entity.main.Useunit;

import com.xmrbi.unware.component.greendao.StoreHouseDao;
import com.xmrbi.unware.component.greendao.UseunitDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storeHouseDaoConfig;
    private final DaoConfig useunitDaoConfig;

    private final StoreHouseDao storeHouseDao;
    private final UseunitDao useunitDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storeHouseDaoConfig = daoConfigMap.get(StoreHouseDao.class).clone();
        storeHouseDaoConfig.initIdentityScope(type);

        useunitDaoConfig = daoConfigMap.get(UseunitDao.class).clone();
        useunitDaoConfig.initIdentityScope(type);

        storeHouseDao = new StoreHouseDao(storeHouseDaoConfig, this);
        useunitDao = new UseunitDao(useunitDaoConfig, this);

        registerDao(StoreHouse.class, storeHouseDao);
        registerDao(Useunit.class, useunitDao);
    }
    
    public void clear() {
        storeHouseDaoConfig.clearIdentityScope();
        useunitDaoConfig.clearIdentityScope();
    }

    public StoreHouseDao getStoreHouseDao() {
        return storeHouseDao;
    }

    public UseunitDao getUseunitDao() {
        return useunitDao;
    }

}
